project_id = "putjowciegpzdheideaf"

[functions.add-admin]
verify_jwt = true

[functions.resend-service]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.migrate-user-profiles]
verify_jwt = false

[functions.suspend-user]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = true

[functions.delete-user-with-transfer]
verify_jwt = true

[functions.calculate-insurance]
verify_jwt = true
